"""校验 quant_flow_latest.json 报告是否满足任务验收。"""
import json
import sys

report = json.load(open('data/reports/quant_flow_latest.json', encoding='utf-8'))
print('=== 总体 ===')
print('status:', report['status'])
print('global_latest_trade_date:', report['global_latest_trade_date'])
print('stale_modules:', report['stale_modules'])
print()
print('=== 各 stage 摘要 ===')
for stage in report['stages']:
    print('  ' + stage['stage'].ljust(30) + ' | ' + stage['status'].ljust(8) + ' | ' + stage['summary'])
print()
print('=== final_brief.data.dragon_eye ===')
fb = report['final_brief']['data']
print('  dragon_eye_explanation:', fb.get('dragon_eye_explanation'))
print('  dragon_eye_partial:', fb.get('dragon_eye_partial'))
print('  dragon_eye_missing_parts:', fb.get('dragon_eye_missing_parts'))
print('  research_output_level:', fb.get('research_output_level'))
print()
print('=== strategy_signals.diagnosis ===')
sig = fb.get('strategy_signals', {})
diag = sig.get('diagnosis', {})
print('  total_scanned:', diag.get('total_scanned'))
print('  buy/sell/watch/no_signal:',
      diag.get('buy_count'), '/', diag.get('sell_count'),
      '/', diag.get('watch_count'), '/', diag.get('no_signal_count'))
print('  blocked_reason:', sig.get('blocked_reason'))
print('  top_blocked_reasons:', diag.get('top_blocked_reasons'))
print()
print('=== portfolio_risk ===')
pr = fb.get('portfolio_risk', {})
print('  status:', report['stages'][5]['status'])
print('  valuation_date:', pr.get('valuation_date'))
print('  valuation_complete:', pr.get('valuation_complete'))
print('  has_quantity_field:', pr.get('summary', {}).get('has_quantity_field'))
print('  total_market_value:', pr.get('summary', {}).get('total_market_value'))
print('  schema:', pr.get('schema'))
print()
print('=== DragonEye 完整性字段（最新完整证据 2026-04-30）===')
de = fb.get('strong_directions', {})
print('  has_ladder:', de.get('has_ladder'))
print('  has_limit_up:', de.get('has_limit_up'))
print('  has_sentiment:', de.get('has_sentiment'))
print('  has_theme_flow:', de.get('has_theme_flow'))
print('  completeness_score:', de.get('completeness_score'))
print('  evidence_date:', de.get('evidence_date'))
print('  missing_parts:', de.get('missing_parts'))
print('  partial_success:', de.get('partial_success'))
print()
print('=== 2026-06-10 partial 状态 ===')
print('  latest_partial_date:', de.get('latest_partial_date'))
print('  latest_partial_status:', de.get('latest_partial_status'))
