"""Read node market metrics generated by Data Auto Update v1."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import pandas as pd

from server.industry_chain.loader import project_root

logger = logging.getLogger(__name__)

DEFAULT_OUTPUT_DIR = project_root() / "data" / "industry"


class NodeMetricsService:
    """Node metrics reader with latest-date selection and old-file fallback."""

    def __init__(self, output_dir: Path | None = None) -> None:
        self.output_dir = output_dir or DEFAULT_OUTPUT_DIR
        self._metrics_df: pd.DataFrame | None = None

    def _load_metrics(self) -> pd.DataFrame:
        if self._metrics_df is not None:
            return self._metrics_df
        for filename in ("industry_node_metrics.parquet", "node_market_metrics.parquet"):
            parquet_path = self.output_dir / filename
            try:
                if parquet_path.exists():
                    self._metrics_df = pd.read_parquet(parquet_path)
                    return self._metrics_df
            except Exception as exc:
                logger.warning("Failed to load %s: %s", parquet_path, exc)
        self._metrics_df = pd.DataFrame()
        return self._metrics_df

    def get_node_metrics(self, chain_id: str, node_id: str, trade_date: str | None = None) -> dict[str, Any]:
        df = self._load_metrics()
        if df.empty:
            return self._empty_metrics()
        try:
            filtered = df[(df["chain_id"] == chain_id) & (df["node_id"] == node_id)]
            if filtered.empty:
                return self._empty_metrics()
            if trade_date:
                filtered = filtered[filtered["trade_date"] == trade_date]
            else:
                latest = filtered["trade_date"].max()
                filtered = filtered[filtered["trade_date"] == latest]
            if filtered.empty:
                return self._empty_metrics()
            return self._row_to_dict(filtered.iloc[0])
        except Exception as exc:
            logger.warning("Query node metrics failed: %s", exc)
            return self._empty_metrics()

    def get_chain_metrics(self, chain_id: str, trade_date: str | None = None) -> dict[str, dict[str, Any]]:
        df = self._load_metrics()
        if df.empty:
            return {}
        try:
            filtered = df[df["chain_id"] == chain_id]
            if filtered.empty:
                return {}
            if trade_date:
                filtered = filtered[filtered["trade_date"] == trade_date]
            else:
                latest = filtered["trade_date"].max()
                filtered = filtered[filtered["trade_date"] == latest]
            return {str(row.get("node_id", "")): self._row_to_dict(row) for _, row in filtered.iterrows()}
        except Exception as exc:
            logger.warning("Query chain metrics failed: %s", exc)
            return {}

    def clear_cache(self) -> None:
        self._metrics_df = None

    def _row_to_dict(self, row: Any) -> dict[str, Any]:
        candidate_count = _get_int(row, "candidate_count", _get_int(row, "candidate_stock_count", _get_int(row, "stock_count")))
        avg_pct_chg = _get_float(row, "avg_pct_chg", _get_float(row, "avg_return_1d"))
        result = {
            "node_id": str(row.get("node_id", "")),
            "chain_id": str(row.get("chain_id", "")),
            "trade_date": str(row.get("trade_date", "")),
            "candidate_count": candidate_count,
            "stock_count": candidate_count,
            "verified_stock_count": _get_int(row, "verified_stock_count"),
            "candidate_stock_count": candidate_count,
            "avg_pct_chg": round(avg_pct_chg, 2),
            "avg_return_1d": round(avg_pct_chg, 2),
            "avg_return_5d": _get_float(row, "avg_return_5d"),
            "max_pct_chg": round(_get_float(row, "max_pct_chg"), 2),
            "limit_up_count": _get_int(row, "limit_up_count"),
            "consecutive_limit_count_max": _get_int(row, "consecutive_limit_count_max"),
            "strong_stock_count": _get_int(row, "strong_stock_count"),
            "total_amount": round(_get_float(row, "total_amount"), 2),
            "main_net_inflow": round(_get_float(row, "main_net_inflow"), 2),
            "amount_change_ratio": round(_get_float(row, "amount_change_ratio"), 2),
            "hot_score": round(_get_float(row, "hot_score"), 2),
            "market_strength": str(row.get("market_strength", "很弱") or "很弱"),
            "provider_summary": str(row.get("provider_summary", "")),
            "updated_at": str(row.get("updated_at", "")),
        }
        return result

    def _empty_metrics(self) -> dict[str, Any]:
        return {
            "node_id": "",
            "chain_id": "",
            "trade_date": "",
            "candidate_count": 0,
            "stock_count": 0,
            "verified_stock_count": 0,
            "candidate_stock_count": 0,
            "avg_pct_chg": 0.0,
            "avg_return_1d": 0.0,
            "avg_return_5d": 0.0,
            "max_pct_chg": 0.0,
            "limit_up_count": 0,
            "consecutive_limit_count_max": 0,
            "strong_stock_count": 0,
            "total_amount": 0.0,
            "main_net_inflow": 0.0,
            "amount_change_ratio": 0.0,
            "hot_score": 0.0,
            "market_strength": "很弱",
            "provider_summary": "",
            "updated_at": "",
        }


def _get_float(row: Any, col: str, default: float = 0.0) -> float:
    try:
        value = row.get(col, default)
        return float(value) if pd.notna(value) else default
    except (TypeError, ValueError):
        return default


def _get_int(row: Any, col: str, default: int = 0) -> int:
    try:
        value = row.get(col, default)
        return int(float(value)) if pd.notna(value) else default
    except (TypeError, ValueError):
        return default
